baseURL = "https://arnoldsm.pages.dev/"
languageCode = 'en-us'
title = 'ArnoldSM - Portfolio & Blog'
theme = 'hugo-noir-v4'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "Arnold Smolinka"
location = "Istanbul, Türkiye"
description = "I do whatever I set my mind to."
profile_image = "/images/profile.png"
discord = "arnold0001"
github = "https://github.com/Strekeos"
github_username = "Strekeos"
email = "absmolinka@gmail.com"
twitter = "https://www.twitter.com/Strekeos"
twitter_username = "Strekeos"
medium = "https://www.medium.com/@johndoe123"
linkedin = "https://www.linkedin.com/in/arnold-sm"
linkedin_username = "Arnold SMOLINKA"
instagram = "https://instagram.com/arnoldsmolinka/"

[[params.honors]]
institution = "Istanbul University"
title = "Environmental Engineering"
date = "June 2020"

[[params.honors]]
institution = "Istanbul Atatürk Anadolu Lisesi"
title = "Math & Science"
date = "June 2015"

[[params.certifications]]
title = "A&CD Assesment Center"
date = "Nov 2022"
url = "https://www.assessment.com.tr/"

[[params.certifications]]
title = "İTÜSEM Finance and Economics Training for Managers"
date = "March 2025" 
url = "https://itusem.itu.edu.tr/"

[[params.certifications]]
title = "Financial Accounting"
date = "March 2025" 
url = "https://www.vizyongrubu.com/akademi/"

[[params.experience]]
company = "VIZYON DENETIM VE SERBEST MUHASEBECI MALI MÜŞAVIRLIK LTD. ŞTI."
role = "Junior Financial Auditor"
period = "Nov 2024 - Present"
logo = "/images/company/vizyon.png"
description = "Junior Financial Auditor focused on audits, reports, and fieldwork."
responsibilities = [
    "Collection, examination, and comparison of financial documents.",
    "Control of Independent Audit Reports and pre-report work.",
    "Preparation of BDDK (Banking Regulation and Supervision Agency) Foreign Currency Reports.",
    "KGK (Public Oversight, Accounting and Auditing Standards Authority) table works.",
    "Fieldwork for stock and cash counting."
]

[[params.experience]]
company = "BİLKENT HOLDİNG TEPE İSG HİZMETLERİ A.Ş. "
role = "Human Resources Specialist"
period = "Sept 2021 - Dec 2023"
logo = "/images/company/tepe.jpg"
description = "Responsible for recruitment processes, onboarding, personnel tracking, and HR process optimization."
responsibilities = [
    "Identifying personnel shortages and preparing personnel shortage reports.",
    "Creating and finding candidate pools.",
    "Conducting recruitment and post-employment interviews.",
    "Managing the entry and exit processes of employment.",
    "Monitoring trial and evaluation processes.",
    "Optimizing human resources processes.",
    "Turkish to English translations."
]

[[params.experience]]
company = "BİLKENT HOLDİNG TEPE İSG HİZMETLERİ A.Ş. "
role = "Data Control Specialist, Human Resources and Admisintrative Affairs Officer"
period = "Sept 2020 - Sept 2021"
logo = "/images/company/tepe.jpg"
description = "Handles HR tasks, expense payments, document control, and Turkish-English translations."
responsibilities = [
    "Data control, Document archiving, Archive reporting.",
    "Recruitment-removal procedures.",
    "Human resources document control and follow-up.",
    "Payment of business expenses.",
    "Supply of tools and materials needed for work.",
    "Turkish to English translations."
]

[[params.experience]]
company = "ZOOM MUSIC"
role = "Production Assistant"
period = "Nov 2018 - Sept 2020"
logo = "/images/company/zoom.png"
description = "Manages tour planning, logistics, and technical support, ensuring smooth concert setup, operation, and teardown."
responsibilities = [
    "Pre-concert setup, continuity during the concerts, post-concert equipment gathering.",
    "Planning tours.",
    "Technical support.",
    "Backstage support.",
    "Planning logistics."
]

[[params.experience]]
company = "BEDROCK CAVE HOTEL"
role = "Night Manager"
period = "July 2018 - Sept 2018 and July 2019 - Sept 2019"
logo = "/images/company/bedrock.png"
description = "Oversees staff discipline, daily preparations, guest check-ins/check-outs, and tour and balloon ride sales."
responsibilities = [
    "Ensuring staff work discipline.",
    "Making daytime preparations.",
    "Supervising night check-ins and check-outs.",
    "Supervising tour and ballon ride sales."
]

[[params.projects]]
title = "QMK Firmware for GMMK Numpad"
description = "Updated firmware for GMMK Numpad"
tech = "QMK, Java, C"
image = "/images/projects/gmmknumpad.png"
link = "https://github.com/Strekeos/custom-qmk-firmware/tree/main/GMMK%20Numpad"

[[params.projects]]
title = "QMK Firmware for Monsgeek M1 V5"
description = "Updated firmware for Monsgeek M1 V5"
tech = "QMK, Java, C"
image = "/images/projects/monsgeekm1v5.png"
link = "https://github.com/Strekeos/custom-qmk-firmware/tree/main/Compiled/Monsgeek%20M1%20V5"

[[params.blogs]]
title = "My First Blog Post"
date = "2025-04-09"
summary = "My first blog post on this website."
tags = ["Blog", "First", "Website"]
content = """
This is my first blog post that I made for my website. AI is great and with help of some models this didn’t even took a day to develop.
"""
link = "https://medium.com/@absmolinka/first-blog-post-720899b25e15"

[[params.blogs]]
title = "My Second Blog Post"
date = "2025-04-09"
summary = "First self hosted blog post."
tags = ["hosting", "blog", "post"]
content = """
This is the second post of the website and the first post that is hosted on the website.
"""
link = "https://arnoldsm.pages.dev/blogs/second-post/"

[[params.blogs]]
title = "Crafting Content with AI: A Guide to AI-Assisted Blog Post Creation"
date = "2025-04-09"
summary = "Explore the strategic integration of Artificial Intelligence in blog writing, maximizing efficiency while maintaining authenticity and quality."
tags = ["AI", "Content Creation", "Blogging", "Artificial Intelligence", "Writing Tools", "Productivity"]
content = """
### Introduction: The AI Revolution in Content Creation

The landscape of digital content creation is undergoing a significant transformation, driven largely by advancements in Artificial Intelligence (AI). For bloggers and content marketers, AI presents unprecedented opportunities to streamline workflows, generate ideas, and enhance productivity. However, leveraging AI effectively requires a strategic approach, balancing technological capabilities with the essential human elements of creativity, critical thinking, and authenticity. This guide explores how to harness AI for blog post creation, transforming it from a mere tool into a powerful collaborator.

### The Strategic Advantages of AI in Blogging

Integrating AI into your blogging process offers several compelling benefits:

1.  **Accelerated Drafting:** AI models can generate initial drafts, outlines, or specific sections of a blog post in a fraction of the time it takes to write manually. This frees up valuable time for refinement, research, and strategic planning.
2.  **Overcoming Writer's Block:** AI serves as an excellent brainstorming partner, suggesting topic ideas, different angles, or introductory hooks when inspiration is lacking.
3.  **Content Ideation & Research:** AI tools can analyze trends, summarize research papers, and identify relevant keywords, providing a solid foundation for informative and engaging content.
4.  **Consistency in Tone and Style:** For brands or publications requiring a consistent voice across multiple authors, AI can be trained or prompted to adhere to specific style guides.

### Best Practices for AI-Assisted Writing

Maximizing the potential of AI requires more than simply feeding it a topic. Consider these best practices:

*   **Precision Prompting:** The quality of AI output is directly proportional to the quality of the input. Craft detailed, specific prompts that clearly outline the desired topic, target audience, tone, key points to cover, and any negative constraints (e.g., topics to avoid).
*   **Iterative Refinement:** Treat the initial AI output as a first draft. Expect to refine, edit, and restructure the content. Use AI iteratively—ask it to expand on points, rephrase sections, or simplify complex ideas.
*   **Fact-Checking and Verification:** AI models, while powerful, can sometimes generate inaccurate or outdated information ("hallucinations"). Rigorous fact-checking against reliable sources is non-negotiable.
*   **Injecting Human Insight and Personality:** AI excels at structure and information synthesis, but it often lacks genuine voice, personal anecdotes, and nuanced perspectives. Your unique insights, experiences, and brand personality are crucial differentiators. Edit heavily to infuse the content with your authentic voice.
*   **SEO Optimization:** While AI can suggest keywords, ensure the final content is strategically optimized for search engines, focusing on user intent, readability, and natural keyword integration.

### Ethical Considerations and Maintaining Authenticity

Using AI in content creation necessitates transparency and ethical awareness:

*   **Disclosure:** Depending on your audience and platform guidelines, consider disclosing the use of AI in content generation. Transparency builds trust.
*   **Avoiding Plagiarism:** Ensure the AI-generated content is original and not merely replicating existing sources. Use plagiarism checkers as a final step.
*   **Ownership and Responsibility:** Ultimately, you are responsible for the accuracy, quality, and ethical implications of the content published under your name or brand, regardless of AI involvement.

### Conclusion: AI as a Collaborator, Not a Replacement

Artificial Intelligence offers powerful tools to augment the blog creation process, enhancing efficiency and overcoming common hurdles. By adopting a strategic approach—focusing on precise prompting, iterative refinement, rigorous verification, and infusing human creativity—bloggers can leverage AI as a valuable collaborator. The future of content creation lies not in full automation, but in the synergistic partnership between human ingenuity and artificial intelligence, resulting in higher quality content produced more effectively.
"""
link = "https://arnoldsm.pages.dev/blogs/crafting-content-with-ai-a-guide-to-ai-assisted-blog-post-creation/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5