# .github/workflows/generate_blog_images.yml
name: Generate Blog Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Keep caching enabled

      - name: Install dependencies
        run: pip install -r requirements.txt # Install from the file

      - name: Generate images
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: python generate_images.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add static/images/blog/
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "Add AI-generated blog images [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi