name: Generate and Commit Image

on:
  push:
    branches:
      - main # Or your specific branch
  workflow_dispatch:

jobs:
  generate-and-commit-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Add this step for debugging ---
      - name: List files in repository root
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing files in root:"
          ls -la
          echo "Listing files in arnoldsm (if exists):"
          ls -la arnoldsm || echo "arnoldsm directory not found"
          echo "Listing files in arnoldsm/content (if exists):"
          ls -la arnoldsm/content || echo "arnoldsm/content directory not found"
          echo "Listing files recursively (use with caution on large repos):"
          ls -R # This will show everything

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Run image generation script
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: python .github/scripts/generate_single_image.py

      - name: Commit and push generated images
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add all generated images in the target directory
          git add arnoldsm/static/images/blogs/*.jpg
          # Check if there are changes to commit
          # Use 'git diff --staged --quiet ||' to only proceed if there are staged changes
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Generate blog images"
            # Add retry logic for push in case of temporary network issues or branch protection conflicts
            for i in 1 2 3; do git push && break || sleep 5; done
          else
            echo "No new images generated or changes detected."
          fi
