name: Generate and Commit Blog Images

on:
  # Trigger on push to the main branch (adjust as needed)
  push:
    branches:
      - main
    # --- IMPORTANT: PATHS FILTER ---
    # Only run this workflow if relevant source files are pushed.
    # Do NOT run if only files in static/images/blogs/ are pushed (prevents loop).
    paths:
      - 'content/blogs/**.md'             # Markdown content changes
      - '.github/scripts/generate_single_image.py' # Script changes
      - '.github/workflows/generate_image.yml'     # Workflow changes
      - 'requirements.txt'                # Dependency changes
    # Note: 'static/images/blogs/**' is intentionally excluded here!
    # --- /IMPORTANT: PATHS FILTER ---

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  generate-and-commit-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "ERROR: requirements.txt not found!"
            exit 1
          fi

      - name: Run image generation script
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python .github/scripts/generate_single_image.py

      - name: Commit and push generated images
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add static/images/blogs/*.jpg || true
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing and pushing..."
            # --- REMOVED [skip ci] ---
            git commit -m "Automated: Generate blog images"
            # --- /REMOVED [skip ci] ---
            git push
          else
            echo "No new images generated or changes detected to commit."
          fi
